---
title: "Impact de la pandémie de COVID-19 sur la mobilité en Wallonie : une analyse spatio-temporelle (2020–2022)"
author: "Youmbijeanne,Tsamo voufo melvanie,Linda tchinda,Sotche Merveil,Masala mundambu nelly"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
---

<!--# Ce travail doit faire entre 15 et 20 pages.-->

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport.-->

La crise sanitaire liée à la COVID-19 a entraîné une transformation majeure des comportements de mobilité. Afin de contenir la diffusion du virus, les autorités ont instauré diverses mesures restrictives, parmi lesquelles les périodes de confinement, la généralisation du télétravail et la limitation des déplacements. Ces dispositifs ont conduit à une baisse significative des flux de déplacement, en particulier en direction des espaces collectifs et des environnements professionnels.

Cette réduction de la mobilité s’est manifestée de manière marquée dans plusieurs secteurs, notamment les déplacements associés aux activités commerciales et récréatives, aux lieux de travail ainsi qu’à l’utilisation des transports publics. L’intensité de ces évolutions n’a cependant pas été constante, mais a suivi les différentes phases de la pandémie, évoluant au rythme des contraintes sanitaires et de leur levée progressive.

## But

<!--% Rédigez le but de ce rapport.-->

Le but de ces analyses est de comprendre et d’expliquer l’évolution de la mobilité, ainsi que l’impact de la pandémie et des mesures anti-Covid sur cette évolution, afin d’identifier les changements observés et d’en tirer des enseignements.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter le données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

## Résultats

<!--% Présentez les analyses les plus pertinents que vous avez sélectionnés. Structurez la section en partie avec des titres explicites de niveau trois.-->

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->
